### ISSUE TITLE
GameController.Files.ReloadFiles

### ISSUE THREAD

**Issue by JamesCrumble** [Queuete/PreloadAlert#1]
Cannot find any connections to ReloadFiles in Core. What is ReloadFiles and where can i find it?

**Comment by Queuete** [comment]
- look into the GameController class and find out "Files" is of type "FilesContainer"
- look into FilesContainer class and there is the "ReloadFiles" method

https://github.com/Queuete/ExileApi/blob/master/Core/PoEMemory/FilesContainer.cs#L233

**Comment by JamesCrumble** [comment]
ohhh, i see, thanks a lot. Seems like i used wrond exileapi, sorry .-.
